### ISSUE TITLE
Add more features - communicate with AirPods like Apple Devices

### ISSUE THREAD

**Issue by kavishdevar** [Project-PixelStar/packages_apps_BtHelper#1]
Hey!

I've managed to reverse engineer airpods functionalities and how they work on apple devices. Currently there's a bug in the AOSP bluetooth stack that doesn't allow it to work though.

Apple uses the L2CAP protocol to communicate with the airpods, they use the PSM 4097 or 0x1001. But the problem with using this is that in flouride, it sends the airpods a packet to check for extended flow control, and wait for the device to respond. But the airpods don't respond to anything until a specific handshake packet is sent first. So android just doesn't continue with the connection.. I commented out the lines in the bluetooth stack and replaced the `libbluetooth_jni.so` (Ask me more about it), and voilà! It worked.. Instead of relying on the advertisements, the btservices can now communicate with the airpods just like an apple device would!! ear-detection, accurate battery percentages, setting anc modes, controlling what the button does, accessiblity settings, controlling adaptive transparency strength (new on app2) can be implemented easily!

But the only problem is that I can build the BtServices app, but it being a soong-built app, takes a long time to build.. and isn't ideal for experimenting. But, I might end up making some changes and making a PR, no promises though

**Comment by Takixamru** [comment]
I was busy , That is my I am responding You This Late.
 Meanwhile, I've read https://github.com/TheParasiteProject/packages_apps_BtHelper/issues/1 This issue & I am requesting you to contact me over telegram .


Regards,
@Takixamru 
 On behalf of Project-Pixelstar Team
